#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

###############################################################################
#  NKP Management Cluster — Pre-flight Validation
#
#  Reads config.json (generated by configure.py) and validates:
#    1. Bootstrap machine tools
#    2. Configuration sanity (names, IPs, CIDRs, node sizing, files)
#    3. Network connectivity (PC, VIP, MetalLB, DNS, NTP)
#    4. Nutanix API (PC auth, PE cluster, subnet, image, storage container)
#    5. Registry reachability (connected mirror or airgap private)
#    6. Proxy settings
#
#  Passwords are prompted at runtime (or read from env vars).
###############################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/config.json"

# ---------------------------------------------------------------------------
# Colors & helpers
# ---------------------------------------------------------------------------
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

PASSED=()
FAILED=()
WARNED=()

pass() { PASSED+=("$1"); echo -e "  ${GREEN}[PASS]${NC} $1"; }
fail() { FAILED+=("$1"); echo -e "  ${RED}[FAIL]${NC} $1"; }
warn() { WARNED+=("$1"); echo -e "  ${YELLOW}[WARN]${NC} $1"; }

print_header() {
  echo ""
  echo "══════════════════════════════════════════════════════════"
  echo "  $1"
  echo "══════════════════════════════════════════════════════════"
}

cfg() { jq -r "$1 // empty" "$CONFIG_FILE"; }

# Try multiple API versions, return first response with .data
pc_api_first() {
  local result=""
  for path in "$@"; do
    result=$(curl "${CURL_OPTS[@]}" \
      -u "${NTX_USER}:${NTX_PASS}" \
      -H "Accept: application/json" \
      -H "X-Nutanix-Client-Type: ui" \
      "${PC_BASE_URL}${path}" 2>/dev/null || echo "")
    if [[ -n "$result" ]] && echo "$result" | jq -e '.data' &>/dev/null; then
      echo "$result"
      return 0
    fi
  done
  echo "$result"
}

# Load config
if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "ERROR: ${CONFIG_FILE} not found. Run configure.py first."
  exit 1
fi

if ! jq empty "$CONFIG_FILE" 2>/dev/null; then
  echo "ERROR: ${CONFIG_FILE} is not valid JSON."
  exit 1
fi

DEPLOYMENT_TYPE=$(cfg '.deployment_type')
AIRGAP_METHOD=$(cfg '.airgap_method')
BUNDLE_DIR=$(cfg '.bundle_dir')
CLUSTER_NAME=$(cfg '.cluster.name')
NTX_ENDPOINT=$(cfg '.nutanix.endpoint')
NTX_PORT=$(cfg '.nutanix.port')
NTX_USER=$(cfg '.nutanix.username')
NTX_INSECURE=$(cfg '.nutanix.insecure')
NTX_TRUST_BUNDLE=$(cfg '.nutanix.additional_trust_bundle')
NTX_PE=$(cfg '.nutanix.prism_element_cluster')
NTX_SUBNET=$(cfg '.nutanix.subnet')
NTX_STORAGE=$(cfg '.nutanix.storage_container')
NET_VIP=$(cfg '.networking.control_plane_vip')
NET_LB=$(cfg '.networking.metallb_ip_range')
NET_DNS=$(cfg '.networking.dns_server')
NET_NTP=$(cfg '.networking.ntp_server')
POD_CIDR=$(cfg '.networking.pod_cidr')
SVC_CIDR=$(cfg '.networking.service_cidr')
CP_COUNT=$(cfg '.nodes.control_plane.count')
W_COUNT=$(cfg '.nodes.worker.count')
W_VCPUS=$(cfg '.nodes.worker.vcpus')
W_MEM=$(cfg '.nodes.worker.memory_gb')
NIB_IMAGE=$(cfg '.images.nib_image')
WORKER_IMAGE=$(cfg '.images.worker_image')
REG_MIRROR_URL=$(cfg '.registry.mirror_url')
REG_MIRROR_CA=$(cfg '.registry.mirror_ca_cert_path')
REG_URL=$(cfg '.registry.registry_url')
REG_USER=$(cfg '.registry.registry_username')
REG_CA=$(cfg '.registry.ca_cert_path')
SSH_USER=$(cfg '.options.ssh_username')
SSH_KEY=$(cfg '.options.ssh_public_key_file')
KIND_IMAGE=$(cfg '.options.kind_cluster_image')
LICENSE=$(cfg '.license.type')
PROXY_HTTP=$(cfg '.proxy.http_proxy')
PROXY_HTTPS=$(cfg '.proxy.https_proxy')

CURL_OPTS=(-s --connect-timeout 10 --max-time 30)
[[ "$NTX_INSECURE" == "true" ]] && CURL_OPTS+=(-k)

PC_BASE_URL="https://${NTX_ENDPOINT}:${NTX_PORT}/api"

# Retreive creds
print_header "Credentials"

if [[ -n "${NUTANIX_PASSWORD:-}" ]]; then
  echo "  Using NUTANIX_PASSWORD from environment."
  NTX_PASS="$NUTANIX_PASSWORD"
else
  read -rsp "  Prism Central password for ${NTX_USER}: " NTX_PASS < /dev/tty
  echo ""
fi

REG_MIRROR_PASS=""
REG_PASS=""

# Registry passwords — not needed for bundle method
if [[ "$AIRGAP_METHOD" != "bundle" ]]; then
  if [[ "$DEPLOYMENT_TYPE" == "connected" && -n "$REG_MIRROR_URL" ]]; then
    if [[ -n "${REGISTRY_MIRROR_PASSWORD:-}" ]]; then
      echo "  Using REGISTRY_MIRROR_PASSWORD from environment."
      REG_MIRROR_PASS="$REGISTRY_MIRROR_PASSWORD"
    else
      read -rsp "  Registry mirror password (Enter to skip): " REG_MIRROR_PASS < /dev/tty
      echo ""
    fi
  fi

  if [[ "$DEPLOYMENT_TYPE" == "airgap" && -n "$REG_MIRROR_URL" ]]; then
    if [[ -n "${REGISTRY_PASSWORD:-}" ]]; then
      echo "  Using REGISTRY_PASSWORD from environment."
      REG_PASS="$REGISTRY_PASSWORD"
    else
      read -rsp "  Registry mirror password: " REG_PASS < /dev/tty
      echo ""
    fi
  fi
fi

# 1. Bootstrap Host Checks
print_header "1. Bootstrap Host Checks"

for tool in docker nkp kubectl jq helm; do
  if command -v "$tool" &>/dev/null; then
    ver=$($tool version --short 2>/dev/null || $tool version 2>/dev/null | head -1 || echo "installed")
    pass "${tool}: ${ver}"
  else
    if [[ "$tool" == "docker" ]]; then
      if command -v podman &>/dev/null; then
        pass "podman (docker alternative): $(podman version --format '{{.Client.Version}}' 2>/dev/null || echo 'installed')"
      else
        fail "${tool}: not found (podman also not found)"
      fi
    else
      fail "${tool}: not found"
    fi
  fi
done

# 2. Configuration Validation
print_header "2. Configuration Validation"

# Deployment type
if [[ "$DEPLOYMENT_TYPE" == "connected" || "$DEPLOYMENT_TYPE" == "airgap" ]]; then
  pass "Deployment type: ${DEPLOYMENT_TYPE}"
else
  fail "Deployment type: '${DEPLOYMENT_TYPE}' — must be 'connected' or 'airgap'"
fi

# Cluster name: lowercase alphanumeric + hyphens, 1-63 chars
if [[ "$CLUSTER_NAME" =~ ^[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$ ]] || [[ "$CLUSTER_NAME" =~ ^[a-z0-9]$ ]]; then
  pass "Cluster name: ${CLUSTER_NAME}"
else
  fail "Cluster name '${CLUSTER_NAME}' — must be lowercase alphanumeric/hyphens, 1-63 chars"
fi

# Control plane count: must be odd
if [[ "$CP_COUNT" =~ ^[0-9]+$ ]] && (( CP_COUNT % 2 == 1 )); then
  pass "Control plane count: ${CP_COUNT} (odd)"
else
  fail "Control plane count: ${CP_COUNT} — must be an odd number (1, 3, 5, 7)"
fi

# Worker count
if [[ "$W_COUNT" =~ ^[0-9]+$ ]] && (( W_COUNT >= 1 )); then
  pass "Worker count: ${W_COUNT}"
else
  fail "Worker count: ${W_COUNT}"
fi

# License-based minimums
if [[ "$LICENSE" == "pro" || "$LICENSE" == "ultimate" ]]; then
  if (( CP_COUNT < 3 )); then
    warn "CP count ${CP_COUNT} < 3 (minimum for ${LICENSE} license)"
  fi
  if [[ "$LICENSE" == "pro" ]] && (( W_COUNT < 4 )); then
    warn "Worker count ${W_COUNT} < 4 (minimum for pro license)"
  fi
  if [[ "$LICENSE" == "ultimate" ]] && (( W_COUNT < 4 )); then
    warn "Worker count ${W_COUNT} < 4 (minimum for ultimate license)"
  fi
fi

# IP format validation
validate_ip() {
  local label="$1" ip="$2"
  if [[ -z "$ip" ]]; then
    fail "${label}: empty"
    return
  fi
  if [[ "$ip" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    pass "${label}: ${ip}"
  else
    fail "${label}: '${ip}' is not a valid IPv4 address"
  fi
}

validate_ip "Control plane VIP" "$NET_VIP"

# MetalLB range: start-end
if [[ "$NET_LB" =~ ^[0-9.]+\-[0-9.]+$ ]]; then
  pass "MetalLB IP range: ${NET_LB}"
else
  fail "MetalLB IP range: '${NET_LB}' — expected format: start_ip-end_ip"
fi

# CIDR validation
validate_cidr() {
  local label="$1" cidr="$2"
  if [[ -z "$cidr" ]]; then
    warn "${label}: not set"
    return
  fi
  if [[ "$cidr" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[0-9]+$ ]]; then
    pass "${label}: ${cidr}"
  else
    fail "${label}: '${cidr}' — expected format: x.x.x.x/prefix"
  fi
}

validate_cidr "Pod CIDR" "$POD_CIDR"
validate_cidr "Service CIDR" "$SVC_CIDR"

# SSH
if [[ -n "$SSH_USER" ]]; then
  pass "SSH username: ${SSH_USER}"
else
  warn "SSH username: not configured (defaults to konvoy)"
fi

EXPANDED_SSH="${SSH_KEY/#\~/$HOME}"
if [[ -n "$SSH_KEY" && -f "$EXPANDED_SSH" ]]; then
  pass "SSH public key: ${SSH_KEY}"
elif [[ -n "$SSH_KEY" ]]; then
  fail "SSH public key not found: ${EXPANDED_SSH}"
else
  warn "SSH public key: not configured"
fi

# Trust bundle (when insecure=false)
if [[ "$NTX_INSECURE" != "true" && -n "$NTX_TRUST_BUNDLE" ]]; then
  EXPANDED_TB="${NTX_TRUST_BUNDLE/#\~/$HOME}"
  if [[ -f "$EXPANDED_TB" ]]; then
    if openssl x509 -in "$EXPANDED_TB" -noout 2>/dev/null; then
      pass "PC trust bundle: ${NTX_TRUST_BUNDLE}"
    else
      fail "PC trust bundle is not a valid x509 cert: ${NTX_TRUST_BUNDLE}"
    fi
  else
    fail "PC trust bundle not found: ${NTX_TRUST_BUNDLE}"
  fi
elif [[ "$NTX_INSECURE" != "true" ]]; then
  warn "PC TLS verification enabled but no trust bundle configured"
fi

# Registry CA cert
if [[ -n "$REG_CA" ]]; then
  EXPANDED_CA="${REG_CA/#\~/$HOME}"
  if [[ -f "$EXPANDED_CA" ]]; then
    if openssl x509 -in "$EXPANDED_CA" -noout 2>/dev/null; then
      pass "Registry CA cert: ${REG_CA}"
    else
      fail "Registry CA cert is not a valid x509 certificate: ${REG_CA}"
    fi
  else
    fail "Registry CA cert not found: ${REG_CA}"
  fi
fi

# Mirror CA cert
if [[ -n "$REG_MIRROR_CA" ]]; then
  EXPANDED_MCA="${REG_MIRROR_CA/#\~/$HOME}"
  if [[ -f "$EXPANDED_MCA" ]]; then
    pass "Mirror CA cert: ${REG_MIRROR_CA}"
  else
    fail "Mirror CA cert not found: ${REG_MIRROR_CA}"
  fi
fi

# Airgap-specific checks
if [[ "$DEPLOYMENT_TYPE" == "airgap" ]]; then
  pass "Airgap method: ${AIRGAP_METHOD:-external}"

  if [[ "$AIRGAP_METHOD" == "bundle" ]]; then
    # Bundle method: check that bundle files exist
    RESOLVED_BD="$BUNDLE_DIR"
    VD=$(ls -d "${BUNDLE_DIR}"/nkp-v* 2>/dev/null | head -1 || true)
    [[ -n "$VD" && -d "$VD" ]] && RESOLVED_BD="$VD"

    BUNDLE_COUNT=$(find "$RESOLVED_BD" -maxdepth 2 -name "*-image-bundle-*.tar" -type f 2>/dev/null | wc -l)
    if [[ $BUNDLE_COUNT -gt 0 ]]; then
      pass "Image bundles found: ${BUNDLE_COUNT} in ${BUNDLE_DIR}"
    else
      fail "No image bundles (*-image-bundle-*.tar) in ${BUNDLE_DIR}"
    fi

    # Bootstrap image: bundle method loads it automatically
    BOOTSTRAP_LOADED=false
    if command -v docker &>/dev/null; then
      if docker image ls --format '{{.Repository}}:{{.Tag}}' 2>/dev/null | grep -q "konvoy-bootstrap"; then
        BOOTSTRAP_LOADED=true
      fi
    fi
    if [[ "$BOOTSTRAP_LOADED" == "true" ]]; then
      pass "Bootstrap image: docker-loaded locally"
    else
      # Check if bootstrap tar exists in bundle dir
      if find "$RESOLVED_BD" -maxdepth 1 -name "konvoy-bootstrap-image-*.tar" -type f 2>/dev/null | grep -q .; then
        warn "Bootstrap image not docker-loaded yet — run: docker load --input konvoy-bootstrap-image-*.tar"
      else
        fail "Bootstrap image tar not found in bundle dir"
      fi
    fi

  else
    # External registry method: need registry-mirror-url
    if [[ -z "$REG_MIRROR_URL" ]]; then
      fail "External airgap requires registry.mirror_url (--registry-mirror-url)"
    fi

    # Bootstrap image: either docker-loaded or --kind-cluster-image
    BOOTSTRAP_LOADED=false
    if command -v docker &>/dev/null; then
      if docker image ls --format '{{.Repository}}:{{.Tag}}' 2>/dev/null | grep -q "konvoy-bootstrap"; then
        BOOTSTRAP_LOADED=true
      fi
    fi

    if [[ -n "$KIND_IMAGE" ]]; then
      pass "Bootstrap image (kind-cluster-image): ${KIND_IMAGE}"
    elif [[ "$BOOTSTRAP_LOADED" == "true" ]]; then
      pass "Bootstrap image: docker-loaded locally"
    else
      fail "Airgap: bootstrap image not found — docker load or set options.kind_cluster_image"
    fi
  fi
fi

# 3. Network checks
print_header "3. Network Connectivity"

# Prism Central reachable on port
if curl "${CURL_OPTS[@]}" -o /dev/null "https://${NTX_ENDPOINT}:${NTX_PORT}" 2>/dev/null; then
  pass "Prism Central reachable: ${NTX_ENDPOINT}:${NTX_PORT}"
else
  fail "Prism Central unreachable: ${NTX_ENDPOINT}:${NTX_PORT}"
fi

# Control plane VIP should NOT be in use
if ping -c 1 -W 2 "$NET_VIP" &>/dev/null; then
  fail "Control plane VIP ${NET_VIP} is already responding — it must be free"
else
  pass "Control plane VIP ${NET_VIP} is free (not responding)"
fi

# MetalLB IPs should NOT be in use
LB_START="${NET_LB%-*}"
LB_END="${NET_LB#*-}"
if [[ -n "$LB_START" ]]; then
  if ping -c 1 -W 2 "$LB_START" &>/dev/null; then
    warn "MetalLB start IP ${LB_START} is already responding — may conflict"
  else
    pass "MetalLB start IP ${LB_START} is free"
  fi
fi

# DNS resolution
if [[ -n "$NET_DNS" ]]; then
  if nslookup "$NTX_ENDPOINT" "$NET_DNS" &>/dev/null 2>&1 || dig @"$NET_DNS" "$NTX_ENDPOINT" +short &>/dev/null 2>&1; then
    pass "DNS server ${NET_DNS} responds"
  else
    warn "DNS server ${NET_DNS} — could not resolve ${NTX_ENDPOINT} (may be IP-only env)"
  fi
else
  warn "DNS server: not configured"
fi

# NTP check
if [[ -n "$NET_NTP" ]]; then
  if command -v ntpdate &>/dev/null; then
    if ntpdate -q "$NET_NTP" &>/dev/null; then
      pass "NTP server ${NET_NTP} reachable"
    else
      warn "NTP server ${NET_NTP} not reachable"
    fi
  elif command -v chronyd &>/dev/null || command -v timedatectl &>/dev/null; then
    pass "NTP server configured: ${NET_NTP} (cannot validate without ntpdate)"
  else
    warn "NTP server ${NET_NTP} — no ntpdate/chrony to validate"
  fi
else
  warn "NTP server: not configured"
fi

# 4. Nutanix API Checks
print_header "4. Nutanix API Validation"

# Auth test — try multiple API versions
AUTH_RESP=$(pc_api_first \
  "/clustermgmt/v4.0.b2/config/clusters?\$limit=1" \
  "/clustermgmt/v4.0/config/clusters?\$limit=1")

if [[ -z "$AUTH_RESP" ]]; then
  fail "Prism Central API: no response"
  PC_AUTH_OK=false
elif echo "$AUTH_RESP" | jq -e '.data' &>/dev/null; then
  pass "Prism Central authentication successful"
  PC_AUTH_OK=true
else
  ERROR_MSG=$(echo "$AUTH_RESP" | jq -r '.message // .error // "unknown error"' 2>/dev/null || echo "auth failed")
  fail "Prism Central authentication failed: ${ERROR_MSG}"
  PC_AUTH_OK=false
fi

if [[ "${PC_AUTH_OK}" == "true" ]]; then

  # PE cluster exists
  PE_RESP=$(pc_api_first \
    "/clustermgmt/v4.0.b2/config/clusters" \
    "/clustermgmt/v4.0/config/clusters")
  PE_FOUND=$(echo "$PE_RESP" | jq -r --arg name "$NTX_PE" \
    '.data[]? | select(.name == $name) | .extId' 2>/dev/null || echo "")
  if [[ -n "$PE_FOUND" ]]; then
    pass "PE cluster '${NTX_PE}' found (extId: ${PE_FOUND})"
  else
    fail "PE cluster '${NTX_PE}' not found in Prism Central"
  fi

  # Subnet exists
  SUBNET_RESP=$(pc_api_first \
    "/networking/v4.0.b1/config/subnets" \
    "/networking/v4.0.a1/config/subnets" \
    "/networking/v4.0/config/subnets")
  SUBNET_FOUND=$(echo "$SUBNET_RESP" | jq -r --arg name "$NTX_SUBNET" \
    '.data[]? | select(.name == $name) | .extId' 2>/dev/null || echo "")
  if [[ -n "$SUBNET_FOUND" ]]; then
    pass "Subnet '${NTX_SUBNET}' found (extId: ${SUBNET_FOUND})"
  else
    fail "Subnet '${NTX_SUBNET}' not found in Prism Central"
  fi

  # Image exists (CP image)
  IMAGE_RESP=$(pc_api_first \
    "/vmm/v4.0.b1/content/images" \
    "/vmm/v4.0/content/images" \
    "/vmm/v4.0.a1/content/images")
  IMAGE_FOUND=$(echo "$IMAGE_RESP" | jq -r --arg name "$NIB_IMAGE" \
    '.data[]? | select(.name == $name) | .extId' 2>/dev/null || echo "")
  if [[ -n "$IMAGE_FOUND" ]]; then
    pass "CP image '${NIB_IMAGE}' found (extId: ${IMAGE_FOUND})"
  else
    fail "CP image '${NIB_IMAGE}' not found in Prism Central"
  fi

  # Worker image (if different from CP)
  if [[ -n "$WORKER_IMAGE" && "$WORKER_IMAGE" != "$NIB_IMAGE" ]]; then
    W_IMG_FOUND=$(echo "$IMAGE_RESP" | jq -r --arg name "$WORKER_IMAGE" \
      '.data[]? | select(.name == $name) | .extId' 2>/dev/null || echo "")
    if [[ -n "$W_IMG_FOUND" ]]; then
      pass "Worker image '${WORKER_IMAGE}' found"
    else
      fail "Worker image '${WORKER_IMAGE}' not found in Prism Central"
    fi
  fi

  # Storage container exists
  SC_RESP=$(pc_api_first \
    "/storage/v4.0.a3/config/storage-containers" \
    "/storage/v4.0/config/storage-containers")
  SC_FOUND=$(echo "$SC_RESP" | jq -r --arg name "$NTX_STORAGE" \
    '.data[]? | select(.name == $name) | .extId // .containerExtId' 2>/dev/null || echo "")
  if [[ -n "$SC_FOUND" ]]; then
    pass "Storage container '${NTX_STORAGE}' found"
  else
    fail "Storage container '${NTX_STORAGE}' not found in Prism Central"
  fi

fi

# 5. Registry Checks
print_header "5. Registry Checks"
# TODO Magic with harbor and projects
# Also add mirror checks and try a mirror pull
check_registry() {
  local label="$1" url="$2" ca="${3:-}"
  local scheme="https" host="$url"

  # Strip scheme if present
  if [[ "$url" =~ ^https?:// ]]; then
    scheme="${url%%://*}"
    host="${url#*://}"
  fi
  host="${host%%/*}"  # Just the host for /v2/

  local extra=()
  [[ -n "$ca" ]] && extra+=(--cacert "${ca/#\~/$HOME}")

  local code
  code=$(curl -s --connect-timeout 10 --max-time 15 "${extra[@]}" \
    -o /dev/null -w "%{http_code}" "${scheme}://${host}/v2/" 2>/dev/null || echo "000")

  if [[ "$code" == "200" || "$code" == "401" ]]; then
    pass "${label} reachable: ${host} (HTTP ${code})"
    return 0
  fi

  # Try other scheme
  local alt="http"
  [[ "$scheme" == "http" ]] && alt="https"
  code=$(curl -s --connect-timeout 10 --max-time 15 "${extra[@]}" \
    -o /dev/null -w "%{http_code}" "${alt}://${host}/v2/" 2>/dev/null || echo "000")
  if [[ "$code" == "200" || "$code" == "401" ]]; then
    pass "${label} reachable: ${host} (HTTP ${code}, ${alt}://)"
    return 0
  fi

  fail "${label} unreachable: ${host}/v2/ (HTTP ${code})"
  return 1
}

if [[ "$DEPLOYMENT_TYPE" == "connected" ]]; then
  if [[ -n "$REG_MIRROR_URL" ]]; then
    check_registry "Registry mirror" "$REG_MIRROR_URL" "$REG_MIRROR_CA" || true
  else
    warn "No registry mirror configured (Docker Hub rate limits may apply)"
  fi
elif [[ "$AIRGAP_METHOD" == "bundle" ]]; then
  # Bundle method: no external registry needed for cluster creation
  pass "Bundle mode: no external registry check needed (internal registry from bundles)"
else
  # External registry method: mirror URL required
  if [[ -n "$REG_MIRROR_URL" ]]; then
    check_registry "Registry mirror" "$REG_MIRROR_URL" "$REG_MIRROR_CA" || true
  else
    fail "External airgap requires registry.mirror_url"
  fi
  # registry_url is for push scripts — check it too if set
  if [[ -n "$REG_URL" && "$REG_URL" != "$REG_MIRROR_URL" ]]; then
    check_registry "Push registry" "$REG_URL" "$REG_CA" || true
  fi
fi

# 6. Proxy Checks
if [[ -n "$PROXY_HTTP" || -n "$PROXY_HTTPS" ]]; then
  print_header "6. Proxy Checks"

  for proxy_var in PROXY_HTTP PROXY_HTTPS; do
    proxy_val="${!proxy_var}"
    [[ -z "$proxy_val" ]] && continue
    if [[ "$proxy_val" =~ ^https?:// ]]; then
      pass "Proxy URL format: ${proxy_val}"
      if curl -s --connect-timeout 5 --proxy "$proxy_val" -o /dev/null "https://${NTX_ENDPOINT}:${NTX_PORT}" 2>/dev/null; then
        pass "Proxy reachable and can reach PC: ${proxy_val}"
      else
        warn "Proxy ${proxy_val} — could not reach PC through it"
      fi
    else
      fail "Proxy URL malformed: ${proxy_val} — expected http:// or https://"
    fi
  done
fi

# Summary
print_header "Summary"

echo ""
echo -e "  ${GREEN}Passed: ${#PASSED[@]}${NC}"
[[ ${#WARNED[@]} -gt 0 ]] && echo -e "  ${YELLOW}Warnings: ${#WARNED[@]}${NC}"
echo -e "  ${RED}Failed: ${#FAILED[@]}${NC}"
echo ""

if [[ ${#FAILED[@]} -gt 0 ]]; then
  echo -e "  ${RED}Failed checks:${NC}"
  for f in "${FAILED[@]}"; do
    echo -e "    ${RED}✗${NC} ${f}"
  done
  echo ""
  echo "  Fix the above issues before creating the management cluster."
  exit 1
else
  echo -e "  ${GREEN}All checks passed — ready to deploy!${NC}"
  exit 0
fi
